site_name: Pipeline de Dados - Ouvidoria (SATC)
site_description: Documentação do projeto de Engenharia de Dados com Spark, Delta Lake e PostgreSQL.
site_author: Bruno M, Gianluca A e Luis Filipe D
site_url: https://github.com/brunomonteirobonifacio/projeto2-engenharia-dados-satc

repo_name: projeto2-engenharia-dados-satc
repo_url: https://github.com/brunomonteirobonifacio/projeto2-engenharia-dados-satc

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: black
      accent: blue
    - scheme: slate
      primary: black
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight

nav:
  - Início: index.md
  - Apache Spark: spark.md
  - Delta Lake: dml_delta.md
  - Delta CSV: csv_to_delta.md
  - Minio CSV PostgreSQL: postgresql_to_minio_csv.md
  - Setup PostgreSQL: setup_potsgresql.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - attr_list